blueprint:
  name: ZHA - Tuya 4-Button Scene Switch
  description: Automate your Tuya 4-Button Scene Switch using ZHA events.
  domain: automation
  input:
    tuya_4button_scene_switch:
      name: Tuya 4-Button Scene Switch
      description: Tuya 4-Button Scene Switch to use
      selector:
        device:
          filter:
            - integration: deconz
              manufacturer: _TZ3000_vp6clf9d
              model: TS0044
            - integration: deconz
              manufacturer: _TZ3000_wkai4ga5
              model: TS0044
    button_one_short_press:
      name: Single Press
      description: Action to run on button 1 (lower-left) single press
      default: []
      selector:
        action: {}
    button_one_double_press:
      name: Double Press
      description: Action to run on button 1 (lower-left) double press
      default: []
      selector:
        action: {}
    button_one_long_press:
      name: Long Press
      description: Action to run on button 1 (lower-left) long press
      default: []
      selector:
         action: {} 
    button_two_short_press:
      name: Single Press
      description: Action to run on button 2 (lower-right) single press
      default: []
      selector:
        action: {}
    button_two_double_press:
      name: Double Press
      description: Action to run on button 2 (lower-right) double press
      default: []
      selector:
        action: {}
    button_two_long_press:
      name: Long Press
      description: Action to run on button 2 (lower-right) long press
      default: []
      selector:
         action: {}  
    button_three_short_press:
      name: Single Press
      description: Action to run on button 3 (upper-right) single press
      default: []
      selector:
        action: {}
    button_three_double_press:
      name: Double Press
      description: Action to run on button 3 (upper-right) double press
      default: []
      selector:
        action: {}
    button_three_long_press:
      name: Long Press
      description: Action to run on button 3 (upper-right) long press
      default: []
      selector:
         action: {} 
    button_four_short_press:
      name: Single Press
      description: Action to run on button 4 (upper-left) single press
      default: []
      selector:
        action: {}
    button_four_double_press:
      name: Double Press
      description: Action to run on button 4 (upper-left) double press
      default: []
      selector:
        action: {}
    button_four_long_press:
      name: Long Press
      description: Action to run on button 4 (upper-left) long press
      default: []
      selector:
         action: {}
mode: restart
max_exceeded: silent
trigger:
- platform: event
  event_type: deconz_event
  event_data:
    device_id: !input 'tuya_4button_scene_switch'
action:
- variables:
    event: '{{ trigger.event.data.event }}'
- choose:
  - conditions: '{{ event == 1002 }}'
    sequence: !input 'button_one_short_press'
  - conditions: '{{ event == 2002 }}'
    sequence: !input 'button_two_short_press'
  - conditions: '{{ event == 3002 }}'
    sequence: !input 'button_three_short_press'
  - conditions: '{{ event == 4002 }}'
    sequence: !input 'button_four_short_press'
  - conditions: '{{ event == 1003 }}'
    sequence: !input 'button_one_long_press'
  - conditions: '{{ event == 2003 }}'
    sequence: !input 'button_two_long_press'
  - conditions: '{{ event == 3003 }}'
    sequence: !input 'button_three_long_press'
  - conditions: '{{ event == 4003 }}'
    sequence: !input 'button_four_long_press'
  - conditions: '{{ event == 1004 }}'
    sequence: !input 'button_one_double_press'
  - conditions: '{{ event == 2004 }}'
    sequence: !input 'button_two_double_press'
  - conditions: '{{ event == 3004 }}'
    sequence: !input 'button_three_double_press'
  - conditions: '{{ event == 4004 }}'
    sequence: !input 'button_four_double_press'
